/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-11 02:06:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8"); 
	String b_num = request.getParameter("b_num"); // 넘긴번호를 문자열로 받기 Get 방식에 의한 전송

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h3>수정하기</h3>\r\n");
      out.write("	<a href=\"./list.jsp\">리스트</a>&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"./view.jsp?b_num=");
      out.print(b_num);
      out.write("\">상세보기</a>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");

	Connection conn = null; //접속객체선언
	PreparedStatement pstmt = null; //쿼리객체선언
	ResultSet rs = null; //쿼리결과(레코트집합)객체선언
	String query = ""; //SQL문법선언
	try {
		Class.forName("com.mysql.jdbc.Driver"); //JDBC 드라이버 로드
		String url = "jdbc:mysql://localhost:3306/mysql"; //접속url
		String user = "root";
		String passwd = "";
		conn = DriverManager.getConnection(url, user, passwd); //DB에 연결
		//out.print(conn);
		//out.print("db conn success");
		
		query = "select * from tblboard where b_num = ?" ; // !핵심문장! ?를 사용해서 b_num에 대응하도록 설정
		pstmt = conn.prepareStatement(query); //쿼리객체생성
		pstmt.setInt(1, Integer.parseInt(b_num)); 
		//위에서 String b_num으로 받아왔기 때문에 
		//정수형으로 형변환을 해야한다. 
		//하지만 기본타입끼리는 (int)abc 가능한데 오른쪽이 객체일때는 이방법으로 할수 없다. 
		//그래서 wrapper클래스 그중 우리가 필요한것이 Integer클라스
		
		rs = pstmt.executeQuery(); // 쿼리 실행해서 결과를 rs에 반환받음
		rs.next(); //첫번째 레코드로 이동 (레코드는 단 1개만검색됨)
		
		String b_subject = rs.getString("b_subject");
		String b_name = rs.getString("b_name");
		String b_contents = rs.getString("b_contents"); //컨텐츠 그대로
		String b_date = rs.getString("b_date");

      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<form method=\"post\" action=\"./update_end.jsp\">\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align = \"center\" width = \"150\">번호</td>\r\n");
      out.write("		<td width=\"300\"><input type=\"text\" name=\"b_num\" value=\"");
      out.print(b_num);
      out.write("\" readonly></td> \r\n");
      out.write("		<!-- 밸류설정해서 노출을 시키면서 건드릴수 있는데 readonly로 해놓아서 건드릴수 없게  -->\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" width=\"150\">제목</td>\r\n");
      out.write("		<td width=\"300\"><input type=\"text\" name=\"b_subject\" value=\"");
      out.print(b_subject);
      out.write("\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>	\r\n");
      out.write("		<td align=\"center\" width=\"150\">작성자</td>\r\n");
      out.write("		<td width=\"300\"><input type=\"text\" name=\"b_name\" value=\"");
      out.print(b_name );
      out.write("\"></td>\r\n");
      out.write("	</tr>	\r\n");
      out.write("	<tr>	\r\n");
      out.write("		<td align=\"center\" width=\"150\">내용</td>\r\n");
      out.write("		<td width=\"300\"><textarea cols=\"50\" rows=\"10\" name=\"b_contents\">");
      out.print(b_contents );
      out.write("</textarea></td>\r\n");
      out.write("		<!-- textarea라서 b_contents = b_contents.replace(\"\\n\", \"<br>\"); 없음 -->\r\n");
      out.write("	</tr>	\r\n");
      out.write("	<tr>	\r\n");
      out.write("		<td align=\"center\" width=\"150\">작성일</td> \r\n");
      out.write("		<td width=\"300\">");
      out.print(b_date );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" colspan=\"2\">\r\n");
      out.write("			<input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</form>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
				
	} catch (Exception e) { // 객체를 생성한 뒤에는 객체를 소멸해줘야 메모리 공간이 여유로워진다.
		out.print(e);
	} finally {
		try {
			if (rs != null)  // 제일 나중에 열린 객체부터 순서대로 닫아준다. rs가 마지막에 열렸으니 여기서는 제일 먼저 닫아준다.
				rs.close();  // close, 종료!
			if (pstmt != null)
				pstmt.close();
			if (conn != null)
				conn.close();
		} catch (Exception ex) {
			out.print(ex);   // 파이널부터 여기까지가 객체 종료 구문이다.
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
